name: example
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  benchmark_harness: ^2.3.1
  decimal: ^3.0.2
  decimal2:
    path: ..
  decimal_type: ^0.0.2
  fixed: ^5.3.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
