name: decimal2
description: Decimals.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

dependencies:
  meta: ^1.16.0
  rational: ^2.2.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
